local profile = {};
local sets = {
    ['Idle'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Malignance Chapeau',
        Neck = 'Warder\'s Charm',
        Ear1 = 'Odnowa Earring',
        Ear2 = 'Telos Earring',
        Body = 'Meg. Cuirie +2',
        Hands = 'Meg. Gloves +2',
        Ring1 = 'Fortified Ring',
        Ring2 = 'Warden\'s Ring',
        Back = 'Archon Cape',
        Waist = 'K. Kachina Belt +1',
        Legs = { Name = 'Carmine Cuisses +1', AugPath='D' },
        Feet = 'Malignance Boots',
    },
    ['Preshot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Telos Earring',
        Ear2 = 'Dedition Earring',
        Body = 'Amini Caban +2',
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Meghanada Ring',
        Ring2 = 'Rajas Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = '"Snapshot"+10' },
        Waist = 'Yemaya Belt',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='D' },
        Feet = 'Meg. Jam. +2',
    },
    ['Midshot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = { Name = 'Arcadian Beret +3', AugTrial=5460 },
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Telos Earring',
        Ear2 = 'Dedition Earring',
        Body = 'Orion Jerkin +3',
        Hands = { Name = 'Adhemar Wrist. +1', AugPath='C' },
        Ring1 = 'Dingir Ring',
        Ring2 = 'Rajas Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = '"Store TP"+10', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'K. Kachina Belt +1',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='C' },
        Feet = 'Malignance Boots',
    },
    ['Melee'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = { Name = 'Adhemar Bonnet +1', AugPath='B' },
        Neck = 'Iskur Gorget',
        Ear1 = 'Cessance Earring',
        Ear2 = 'Telos Earring',
        Body = { Name = 'Adhemar Jacket +1', AugPath='B' },
        Hands = { Name = 'Adhemar Wrist. +1', AugPath='A' },
        Ring1 = 'Epona\'s Ring',
        Ring2 = 'Petrov Ring',
        Back = 'Blithe Mantle',
        Waist = 'Windbuffet Belt +1',
        Legs = { Name = 'Carmine Cuisses +1', AugPath='D' },
        Feet = { Name = 'Herculean Boots', Augment = { [1] = '"Triple Atk."+3', [2] = 'Accuracy+15', [3] = 'Attack+12', [4] = 'DEX+2' } },
    },
    ['DoubleShot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = { Name = 'Arcadian Beret +3', AugTrial=5460 },
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Cessance Earring',
        Ear2 = 'Dedition Earring',
        Body = { Name = 'Arc. Jerkin +3', AugTrial=5482 },
        Hands = 'Oshosi Gloves +1',
        Ring1 = 'Dingir Ring',
        Ring2 = { Name = 'Cacoethic Ring +1', AugPath='A' },
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = '"Store TP"+10', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'K. Kachina Belt +1',
        Legs = 'Oshosi Trousers',
        Feet = 'Oshosi Leggings',
    },
    ['BarrageSet'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = { Name = 'Arcadian Beret +3', AugTrial=5460 },
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Cessance Earring',
        Ear2 = 'Telos Earring',
        Body = { Name = 'Arc. Jerkin +3', AugTrial=5482 },
        Hands = 'Orion Bracers +2',
        Ring1 = 'Dingir Ring',
        Ring2 = { Name = 'Cacoethic Ring +1', AugPath='A' },
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = '"Store TP"+10', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'K. Kachina Belt +1',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='C' },
        Feet = 'Orion Socks +2',
    },
    ['Sharpshot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = { Name = 'Arcadian Beret +3', AugTrial=5460 },
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Cessance Earring',
        Ear2 = 'Telos Earring',
        Body = { Name = 'Arc. Jerkin +3', AugTrial=5482 },
        Hands = 'Orion Bracers +2',
        Ring1 = 'Dingir Ring',
        Ring2 = { Name = 'Cacoethic Ring +1', AugPath='A' },
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = '"Store TP"+10', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'K. Kachina Belt +1',
        Legs = 'Orion Braccae +1',
        Feet = 'Orion Socks +2',
    },
    ['VelocityShot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Cessance Earring',
        Ear2 = 'Dedition Earring',
        Body = 'Amini Caban +2',
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Meghanada Ring',
        Ring2 = 'Rajas Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = '"Snapshot"+10' },
        Waist = 'Yemaya Belt',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='D' },
        Feet = 'Meg. Jam. +2',
    },
    ['LastStand'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Ishvara Earring',
        Ear2 = 'Telos Earring',
        Body = 'Amini Caban +2',
        Hands = 'Meg. Gloves +2',
        Ring1 = 'Karieyh Ring',
        Ring2 = 'Dingir Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = 'Weapon skill damage +10%', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'Fotia Belt',
        Legs = { Name = 'Arc. Braccae +3', AugTrial=5526 },
        Feet = { Name = 'Adhe. Gamashes +1', AugPath='C' },
    },
    ['Wildfire'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Friomisi Earring',
        Ear2 = 'Novio Earring',
        Body = { Name = 'Cohort Cloak +1', AugPath='A' },
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Karieyh Ring',
        Ring2 = 'Dingir Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = 'Weapon skill damage +10%', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'Eschan Stone',
        Legs = { Name = 'Arc. Braccae +3', AugTrial=5526 },
        Feet = { Name = 'Herculean Boots', Augment = { [1] = '"Mag. Atk. Bns."+17', [2] = 'Mag. Acc.+17', [3] = 'Weapon skill damage +2%', [4] = 'Accuracy+3', [5] = 'Attack+3', [6] = 'Pet: Mag. Acc.+19' } },
    },
    ['Coronach'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Ishvara Earring',
        Ear2 = 'Telos Earring',
        Body = 'Amini Caban +2',
        Hands = 'Meg. Gloves +2',
        Ring1 = 'Karieyh Ring',
        Ring2 = 'Dingir Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = 'Weapon skill damage +10%', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'Fotia Belt',
        Legs = { Name = 'Arc. Braccae +3', AugTrial=5526 },
        Feet = 'Meg. Jam. +2',
    },
    ['Trueflight'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Friomisi Earring',
        Ear2 = 'Novio Earring',
        Body = { Name = 'Cohort Cloak +1', AugPath='A' },
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Karieyh Ring',
        Ring2 = 'Dingir Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Magic Damage+20', [2] = 'AGI+20', [3] = 'Mag. Acc.+20' } },
        Waist = 'Eschan Stone',
        Legs = { Name = 'Arc. Braccae +3', AugTrial=5526 },
        Feet = { Name = 'Herculean Boots', Augment = { [1] = '"Mag. Atk. Bns."+17', [2] = 'Mag. Acc.+17', [3] = 'Weapon skill damage +2%', [4] = 'Accuracy+3', [5] = 'Attack+3', [6] = 'Pet: Mag. Acc.+19' } },
    },
    ['Snipershot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Ishvara Earring',
        Ear2 = 'Dedition Earring',
        Body = 'Amini Caban +2',
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Meghanada Ring',
        Ring2 = 'Rajas Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = '"Snapshot"+10' },
        Waist = 'Yemaya Belt',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='D' },
        Feet = 'Meg. Jam. +2',
    },
    ['NumbingShot'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Ishvara Earring',
        Ear2 = 'Dedition Earring',
        Body = 'Amini Caban +2',
        Hands = { Name = 'Carmine Fin. Ga. +1', AugPath='D' },
        Ring1 = 'Meghanada Ring',
        Ring2 = 'Rajas Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = '"Snapshot"+10' },
        Waist = 'Yemaya Belt',
        Legs = { Name = 'Adhemar Kecks +1', AugPath='D' },
        Feet = 'Meg. Jam. +2',
    },
    ['SavageBlade'] = {
        Main = { Name = 'Perun +1', AugPath='A' },
        Range = { Name = 'Fomalhaut', AugPath='A' },
        Ammo = 'Chrono Bullet',
        Head = 'Orion Beret +3',
        Neck = { Name = 'Scout\'s Gorget +2', AugPath='A' },
        Ear1 = 'Ishvara Earring',
        Ear2 = 'Telos Earring',
        Body = 'Meg. Cuirie +2',
        Hands = 'Meg. Gloves +2',
        Ring1 = 'Apate Ring',
        Ring2 = 'Karieyh Ring',
        Back = { Name = 'Belenus\'s Cape', Augment = { [1] = 'Rng.Acc.+20', [2] = 'Weapon skill damage +10%', [3] = 'AGI+30', [4] = 'Rng.Atk.+20' } },
        Waist = 'Sailfi Belt +1',
        Legs = { Name = 'Arc. Braccae +3', AugTrial=5526 },
        Feet = 'Meg. Jam. +2',
    },
};
profile.Sets = sets;

profile.Packer = {
};

profile.OnLoad = function()
    gSettings.AllowAddSet = true;
end

profile.OnUnload = function()
end

profile.HandleCommand = function(args)
end

profile.HandleDefault = function()
end

profile.HandleAbility = function()
end

profile.HandleItem = function()
end

profile.HandlePrecast = function()
end

profile.HandleMidcast = function()
end

profile.HandlePreshot = function()
end

profile.HandleMidshot = function()
end

profile.HandleWeaponskill = function()
end

return profile;